/**
 * @file main.c
 * @brief ESP32 FreeRTOS Event Group demonstration for sensor synchronization.
 * * This file contains a practical example of using FreeRTOS Event Groups 
 * to synchronize multiple tasks in an ESP-IDF project. Three sensor tasks 
 * simulate data generation and signal their completion, while a processing 
 * task waits for all three before calculating the average.
 * * @author Lisandry Azuaje/lisandry
 * @date 2026-04-08
 */

#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "esp_random.h"

/**
 * @brief Handle for the FreeRTOS event group used for task synchronization.
 */
EventGroupHandle_t xHandle = NULL;

/** * @defgroup EventBits Sensor Event Flag Bits
 * @brief Bit definitions for the event group to track each sensor's status.
 * @{
 */
#define EVENT_SENSOR1 (1 << 0) /*!< Bit 0: Indicates Sensor 1 has generated data */
#define EVENT_SENSOR2 (1 << 1) /*!< Bit 1: Indicates Sensor 2 has generated data */
#define EVENT_SENSOR3 (1 << 2) /*!< Bit 2: Indicates Sensor 3 has generated data */
/** @} */

/** * @defgroup SensorData Global Sensor Data Variables
 * @brief Global variables to store the latest values generated by the tasks.
 * @{
 */
float valor_sensor1 = 0; /*!< Latest value from Sensor 1 */
float valor_sensor2 = 0; /*!< Latest value from Sensor 2 */
float valor_sensor3 = 0; /*!< Latest value from Sensor 3 */
/** @} */


/**
 * @brief Task that simulates Sensor 1 data generation.
 * * This task runs in an infinite loop, generating a random float value 
 * every 1000 milliseconds. After updating the global variable, it sets 
 * the EVENT_SENSOR1 bit in the event group to notify the processing task.
 * * @param pvParameters Pointer to task parameters (not used).
 */
void TaskSensor1(void *pvParameters)
{
    while (1) {
        vTaskDelay(pdMS_TO_TICKS(1000)); 
        
        /* Generates a fake floating-point value between 0.0 and 9.9 */
        valor_sensor1 = (esp_random() % 100) / 10.0; 
        ESP_LOGE("Sensor1", "Sensor 1 generated data: %.1f\n", valor_sensor1);
        
        /* Signal that Sensor 1 data is ready */
        xEventGroupSetBits(xHandle, EVENT_SENSOR1);
    }
}

/**
 * @brief Task that simulates Sensor 2 data generation.
 * * This task runs in an infinite loop, generating a random float value 
 * every 1000 milliseconds. After updating the global variable, it sets 
 * the EVENT_SENSOR2 bit in the event group to notify the processing task.
 * * @param pvParameters Pointer to task parameters (not used).
 */
void TaskSensor2(void *pvParameters)
{
    while (1) {
        vTaskDelay(pdMS_TO_TICKS(1000)); 
        
        valor_sensor2 = (esp_random() % 100) / 10.0; 
        ESP_LOGE("Sensor2", "Sensor 2 generated data: %.1f\n", valor_sensor2);

        xEventGroupSetBits(xHandle, EVENT_SENSOR2);
    }
}

/**
 * @brief Task that simulates Sensor 3 data generation.
 * * This task runs in an infinite loop, generating a random float value 
 * every 1000 milliseconds. After updating the global variable, it sets 
 * the EVENT_SENSOR3 bit in the event group to notify the processing task.
 * * @param pvParameters Pointer to task parameters (not used).
 */
void TaskSensor3(void *pvParameters)
{
    while (1) {
        vTaskDelay(pdMS_TO_TICKS(1000)); 
        
        valor_sensor3 = (esp_random() % 100) / 10.0; 
        ESP_LOGE("Sensor3", "Sensor 3 generated data: %.1f\n", valor_sensor3);

        xEventGroupSetBits(xHandle, EVENT_SENSOR3);
    }
}

/**
 * @brief Task responsible for synchronizing data and performing calculations.
 * * This task blocks until all three sensor events are signaled within the 
 * event group. Once synchronized, it calculates the sum and the average 
 * of the generated data. The event bits are automatically cleared upon exit.
 * * @param pvParameters Pointer to task parameters (not used).
 */
void TaskProcessamento(void *pvParameters)
{
    /* Mask of all bits the task needs to wait for */
    const EventBits_t bits_para_aguardar = (EVENT_SENSOR1 | EVENT_SENSOR2 | EVENT_SENSOR3);
    
    while (1) {
        /*
         * Wait for all defined events to be triggered.
         * Parameter 3 (pdTRUE): Automatically clears the bits when condition is met.
         * Parameter 4 (pdTRUE): Wait for ALL bits (AND logic).
         */
        xEventGroupWaitBits(
            xHandle,
            bits_para_aguardar,
            pdTRUE, 
            pdTRUE, 
            portMAX_DELAY
        );
        
        ESP_LOGE("Processamento", "Values received: Sensor1=%.1f, Sensor2=%.1f, Sensor3=%.1f\n", 
                 valor_sensor1, valor_sensor2, valor_sensor3);

        /* Perform simple processing (Sum and Average) */
        float soma = valor_sensor1 + valor_sensor2 + valor_sensor3;
        float media = soma / 3.0;

        ESP_LOGE("Processamento", "Sensors Average: %.2f\n", media);
        ESP_LOGE("Processamento", "Sensors Sum: %.2f\n", soma);
    }
}

/**
 * @brief Main application entry point.
 * * Initializes the FreeRTOS event group and creates the sensor and 
 * processing tasks. The processing task is assigned a higher priority 
 * to ensure immediate execution once data is available.
 */
void app_main(void)
{
    /* Initialize the event group */
    xHandle = xEventGroupCreate();
    
    if (xHandle != NULL) {
        ESP_LOGI("main", "Event group created successfully.");

        /* Create producer tasks (Sensors) with standard priority 1 */
        xTaskCreate(TaskSensor1, "Sensor1", 2048, NULL, 1, NULL);
        xTaskCreate(TaskSensor2, "Sensor2", 2048, NULL, 1, NULL);
        xTaskCreate(TaskSensor3, "Sensor3", 2048, NULL, 1, NULL);
        
        /* Create consumer task (Processing) with higher priority 2 */
        xTaskCreate(TaskProcessamento, "Processa", 2048, NULL, 2, NULL);

        ESP_LOGI("main", "All tasks created and scheduled successfully.");
    } else {
        ESP_LOGE("main", "Failed to create event group. System halted.");
    }
}